SELECT *
FROM customershoppingbehavior

--Q.1 WHat is the total revenue generated by male vs. female customers?
SELECT gender,
SUM(purchase_amount) As total_reveune
FROM customershoppingbehavior
GROUP BY gender

--Q.2 Which customers used a discount but still spent more than average purchase amount?
SELECT *
FROM customershoppingbehavior
WHERE discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM CustomerShoppingBehavior)

--Q.3 Which are the top 5 products with highers average review rating?
SELECT TOP 5 item_purchased,
ROUND(AVG(review_rating),2)  AS avg_rating
FROM customershoppingbehavior
GROUP BY item_purchased
ORDER BY avg_rating DESC;

--Q.4 Compare the average purhase amounts between standard and express shipping.
SELECT shipping_type,
AVG(purchase_amount) as Average_amount
FROM CustomerShoppingBehavior
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type

--Q.5 Do suscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(*) AS no_of_customers,
CAST(AVG(purchase_amount) AS DECIMAL(10,2)) AS Avg_spend,
ROUND(SUM(purchase_amount),2) AS total_spend
FROM customershoppingbehavior
GROUP BY subscription_status

--Q.6 Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied= 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customershoppingbehavior
GROUP BY item_purchased
ORDER BY discount_rate DESC

--Q.7 Segment customers into New, Returning and loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS(
	SELECT customer_id, previous_purchases,
	CASE WHEN previous_purchases = 1 THEN 'NEW' 
		WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
		ELSE 'Loyal'
		END AS customer_segment
	FROM customershoppingbehavior
)

SELECT customer_segment,
	COUNT(*) AS "Number of customers"
FROM customer_type
GROUP BY customer_segment

--Q.8 What are the top 3 most purchased products within each category?
WITH item_counts AS (
SELECT item_purchased, category,
COUNT(*) AS Total_orders,
ROW_NUMBER () OVER(PARTITION BY category ORDER BY COUNT(*) DESC) AS item_rank
FROM CustomerShoppingBehavior
GROUP BY item_purchased, category
)
SELECT *
FROM item_counts 
WHERE item_rank<=3

--Q.9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS reepeat_buyers
FROM CustomerShoppingBehavior
WHERE previous_purchases  >5
GROUP BY subscription_status


--Q.10 What is the revenue contribution of each age group?
SELECT age_group,
100 * SUM(purchase_amount)/ SUM(SUM(purchase_amount)) OVER() AS percent_contribution
FROM CustomerShoppingBehavior
GROUP BY age_group
ORDER BY percent_contribution DESC